volumes:
    redis:
    postgres:
    rabbitmq:
    media:

services:
    app:
        build: ./backend
        environment:
            POSTGRESQL_USER: $POSTGRESQL_USER
            POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
            POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE

            REDIS_HOST: $REDIS_HOST
            DOCKER_POSTGRESQL_HOST: $DOCKER_POSTGRESQL_HOST
            DEFAULT_POSTGRESQL_HOST: $DEFAULT_POSTGRESQL_HOST

            RABBITMQ_HOST: $RABBITMQ_HOST
            RABBITMQ_USERNAME: $RABBITMQ_USERNAME
            RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD

            DEBUG: $DEBUG
            SERVER_URL: $SERVER_URL
            PYTHONUNBUFFERED: 1
            SQLALCHEMY_WARN_20: 1
        volumes:
            - media:/user_media
        deploy:
            replicas: $APP_REPLICAS
        depends_on:
            redis:
                condition: service_started
            postgres:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    daemons:
        build:
            context: ./backend
            dockerfile: daemons.dockerfile
        environment:
            POSTGRESQL_USER: $POSTGRESQL_USER
            POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
            POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE

            REDIS_HOST: $REDIS_HOST
            DOCKER_POSTGRESQL_HOST: $DOCKER_POSTGRESQL_HOST
            DEFAULT_POSTGRESQL_HOST: $DEFAULT_POSTGRESQL_HOST

            RABBITMQ_HOST: $RABBITMQ_HOST
            RABBITMQ_USERNAME: $RABBITMQ_USERNAME
            RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD

            DEBUG: $GLOBAL_DAEMONS_DEBUG
            PYTHONUNBUFFERED: 1
            SQLALCHEMY_WARN_20: 1
        volumes:
            - ~/db_backups:/var/lib/postgres_backups
        depends_on:
            redis:
                condition: service_started
            postgres:
                condition: service_started
            rabbitmq:
                condition: service_healthy

    postgres:
        image: postgres:14-alpine
        ports:
            - "127.0.0.1:5433:5432"
        environment:
            POSTGRES_DB: $POSTGRESQL_DATABASE
            POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
            PGDATA: /var/lib/postgresql/data  # to not lose data on image updates
            # https://stackoverflow.com/a/62301253
        volumes:
            - postgres:/var/lib/postgresql/data

    nginx:
        image: nginx:1.21-alpine
        ports:
            - "80:80"
        volumes:
            - /var/log/nginx:/var/log/nginx
            - ./docker_files/nginx.dev.conf:/etc/nginx/nginx.conf:ro
            - media:/user_media
        depends_on:
            - app

    redis:
        image: redis:7-alpine
        command: --loglevel warning
        ports:
            - "127.0.0.1:6380:6379"
        volumes:
            - redis:/data

    rabbitmq:
        image: rabbitmq:3.10-management-alpine
        hostname: rabbitmq
        ports:
            - "5673:5672"
            - "15673:15672"
        volumes:
            - rabbitmq:/var/lib/rabbitmq
            - ./docker_files/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        environment:
            RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
        healthcheck:
          test: ["CMD", "nc", "-z", "localhost", "5672"]
          interval: 3s
          timeout: 5s
          retries: 3
          start_period: 1s
